apps/medicines/urls.py
from django.urls import path, include
from apps.medicines import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'medicines'

medicines_patterns = [
    path('', views.medicine_list, name='home'),
    path('<int:pk>/', views.medicine_detail, name='medicines-detail'),
    path('crear/', views.medicine_create, name='medicines-create'),
    path('<int:pk>/editar/', views.medicine_update, name='medicines-edit'),
    path('<int:pk>/eliminar/', views.medicine_delete, name='medicines-delete')
]

symptoms_patterns = [
    path('', views.symptom_list, name='symptoms-list'),
    path('<int:pk>/', views.symptom_detail, name='symptoms-detail'),
    path('crear/', views.symptom_create, name='symptoms-create'),
    path('<int:pk>/editar/', views.symptom_update, name='symptoms-edit'),
    path('<int:pk>/eliminar/', views.symptom_delete, name='symptoms-delete')
]

urlpatterns = [
    path('', views.log_in, name='log-in'),
    path('log-out/', views.log_out, name='log-out'),
    path('sintomas/', include(symptoms_patterns)),
    path('medicamentos/', include(medicines_patterns))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Registrar las URLs de tu aplicación aquí
    path('', include('apps.medicines.urls')),
]

# Para servir archivos estáticos en desarrollo
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/medicines/models.py
from django.db import models
from django.urls import reverse_lazy


# Create your models here.

class BaseName(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre')
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Symptoms(BaseName):
    description = models.CharField(max_length=256, verbose_name='Descripcion del sintoma', blank=True)
    
    class Meta:
        verbose_name = 'Sintoma'
        verbose_name_plural = 'Sintomas'

    def get_edit_url(self):
        return reverse_lazy('medicines:symptoms-edit', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse_lazy('medicines:symptoms-delete', kwargs={'pk': self.pk})

    def get_detail_url(self):
        return reverse_lazy('medicines:symptoms-detail', kwargs={'pk': self.pk})



class Medicines(BaseName):
    description = models.CharField(max_length=256, verbose_name='Descripcion del medicamento')
    brand = models.CharField(max_length=10, verbose_name='Marca')
    laboratory = models.CharField(max_length=10, verbose_name='Laboratorio')
    image = models.ImageField(upload_to='medicines', verbose_name='Imagen', blank=True)
    symptom = models.ManyToManyField(Symptoms, verbose_name='Sintoma', blank=True)

    class Meta:
        verbose_name = 'Medicamento'
        verbose_name_plural = 'Medicamentos'

    def get_edit_url(self):
        return reverse_lazy('medicines:medicines-edit', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse_lazy('medicines:medicines-delete', kwargs={'pk': self.pk})

    def get_detail_url(self):
        return reverse_lazy('medicines:medicines-detail', kwargs={'pk': self.pk})

apps/medicines/forms.py
from django import forms
from .models import Medicines, Symptoms


class MedicinesForm(forms.ModelForm):
    class Meta:
        model = Medicines
        fields = '__all__'

class SymptomsForm(forms.ModelForm):
    class Meta:
        model = Symptoms
        fields = '__all__'


class LoginForm(forms.Form):
    username = forms.CharField(label='Usuario')
    password = forms.CharField(widget=forms.PasswordInput, label="Contraseña")

apps/medicines/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .models import Medicines, Symptoms
from .forms import MedicinesForm, LoginForm, SymptomsForm


# Create your views here.


def log_in(request):
    # Diccionario que almacena los datos que enviamos a la vista
    form = LoginForm(
        request.POST or None
    )
    context = {'message': None, 'form': form}
    if request.POST and form.is_valid():
        # Verificar credenciales
        # Devuelve un objeto User si las credenciales son válidas.
        # Si las credenciales no son válidas, devuelve None
        user = authenticate(**form.cleaned_data)
        if user is not None:
            # Verificar si el usuario esta activo
            if user.is_active:
                # Adjuntar usuario autenticado a la sesión actual
                login(request, user)
                # Redireccionar a una vista utilizando el nombre de la url
                return redirect('medicines:home')
            else:
                context['message'] = 'El usuario ha sido desactivado'
        else:
            context['message'] = 'Usuario o contraseña incorrecta'
    return render(request, 'medicines/login.html', context)


# decorador para restringir el acceso a solo usuarios autenticados
@login_required
def log_out(request):
    logout(request)
    return redirect('medicines:log-in')


@login_required
def medicine_list(request):
    medicines = Medicines.objects.all()
    return render(request, 'medicines/index.html', {'medicines': medicines})


@login_required
def medicine_detail(request, pk):
    try:
        # recuperamos el objeto mediante la
        # API de abstracción de base de datos
        # que ofrece Django
        m = Medicines.objects.get(pk=pk)
    except Medicines.DoesNotExist:
        raise Http404("Este medicamento no existe")

    # version con shortcuts de django, equivalente al codigo anterior
    # m = get_object_or_404(Medicines, pk=pk)
    return render(request, 'medicines/detail.html', {'medicine': m})


@login_required
def medicine_create(request, **kwargs):
    # Intanciamos la clase form
    # si el diccionario request.POST no esta vacio
    # la instancia se creara con dichos datos, sino estara vacia
    form = MedicinesForm(
        request.POST or None,
        request.FILES or None
    )
    # Comprobamos que la peticion es del motodo POST
    # y que el formulario es valido
    if request.POST and form.is_valid():
        # Guardamos el objeto
        form.save()
        # redirigir a una nueva URL
        return redirect('medicines:home')
    return render(request, 'medicines/form.html', {'form': form})


def medicine_update(request, **kwargs):
    # recuperamos el objeto a actualizar
    medicine = Medicines.objects.get(pk=kwargs.get('pk'))
    # inicializamos el formulario con el objeto recuperado
    if request.method == 'POST':
        form = MedicinesForm(request.POST, request.FILES, instance=medicine)
        if form.is_valid():
            form.save()
            return redirect('medicines:home')
    else:
        # Si no es una solicitud POST, simplemente muestra el formulario con los datos existentes
        form = MedicinesForm(instance=medicine)
    return render(request, 'medicines/form.html', {'form': form})


@login_required
def medicine_delete(request, **kwargs):
    medicine = Medicines.objects.get(pk=kwargs.get('pk'))
    medicine.delete()
    return redirect('medicines:home')


@login_required
def symptom_list(request):
    symptoms = Symptoms.objects.all()
    return render(request, 'medicines/symptom/symptom_list.html', {'symptoms': symptoms})

@login_required
def symptom_detail(request, pk):
    try:
        # recuperamos el objeto mediante la
        # API de abstracción de base de datos
        # que ofrece Django
        s = Symptoms.objects.get(pk=pk)
    except Symptoms.DoesNotExist:
        raise Http404("Este sintoma no existe")

    return render(request, 'medicines/symptom/detail.html', {'symptoms': s})


@login_required
def symptom_create(request, **kwargs):
    # Intanciamos la clase form
    # si el diccionario request.POST no esta vacio
    # la instancia se creara con dichos datos, sino estara vacia
    form = SymptomsForm(
        request.POST or None,
        request.FILES or None
    )
    # Comprobamos que la peticion es del motodo POST
    # y que el formulario es valido
    if request.POST and form.is_valid():
        # Guardamos el objeto
        form.save()
        # redirigir a una nueva URL
        return redirect('medicines:symptoms-list')
    return render(request, 'medicines/symptom/form.html', {'form': form})


@login_required
def symptom_update(request, **kwargs):
    # recuperamos el objeto a actualizar
    symptom = Symptoms.objects.get(pk=kwargs.get('pk'))
    # inicializamos el formulario con el objeto recuperado
    form = SymptomsForm(
        request.POST or None,
        instance=symptom
    )
    if request.POST and form.is_valid():
        form.save()
        return redirect('medicines:symptoms-list')
    return render(request, 'medicines/symptom/form.html', {'form': form})


@login_required
def symptom_delete(request, **kwargs):
    symptom = Symptoms.objects.get(pk=kwargs.get('pk'))
    print(symptom)
    symptom.delete()
    return redirect('medicines:symptoms-list')

apps/medicines/templates/medicines/symptom/detail.html
{% extends 'medicines/fragments/base.html' %}
{% block main-content %}
<div class="row">
    <div class="col s8 offset-s2">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ symptoms.name}}</span>
                <p><b>Descripcion: </b>{{ symptoms.description }}</p>
                <p><b>Creado: </b>{{ symptoms.created }}</p>
                <p><b>Ultima actualizacion: </b>{{ symptoms.updated }}</p>
            </div>
            <div class="card-action">
                <a href="{{ symptoms.get_edit_url }}">Editar</a>
                <a href="{{ symptoms.get_delete_url }}">Eliminar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/medicines/templates/medicines/symptom/form.html
{% extends 'medicines/fragments/base.html' %}
{% block main-content %}
    <div class="row">
        <div class="col s8 offset-s2">
            {% include 'medicines/fragments/forms.html' %}
        </div>
    </div>
{% endblock %}

apps/medicines/templates/medicines/symptom/symptom_list.html
{% extends 'medicines/fragments/base.html' %}
{% block main-content %}
<div class="row">
    <div class="col s12">
        <a class="waves-effect waves-light btn right light-blue darken-1" href="{% url 'medicines:symptoms-create' %}"><i
                class="material-icons left">add</i>Agregar sintoma</a>
    </div>
    <div class="row">
        <div class="col s12">
            {% if not symptoms %}
            <div class="card-panel orange" style="text-align: center;">
                <span class="white-text ">No hay registros actualmente</span>
            </div>
            {% else %}
            <table class="striped centered">
                <thead>
                    <tr>
                        <th width="20%">Nombre</th>
                        <th>Descripcion</th>
                        <th>Creacion</th>
                        <th>Ultima actualizacion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for symptom_item in symptoms %}
                    <tr>
                        <td width="20%">{{ symptom_item.name }}</td>
                        <td width="20%">{{ symptom_item.description }}</td>
                        <td>{{ symptom_item.created | timesince }}</td>
                        <td>{{ symptom_item.updated | timesince }}</td>
                        <td width="20%">
                            <a class="btn-floating btn-small waves-effect waves-light red"
                                href="{{ symptom_item.get_edit_url }}"><i class="material-icons">edit</i></a>
                            <a class="btn-floating btn-small waves-effect waves-light blue"
                                href="{{ symptom_item.get_delete_url }}"><i class="material-icons">delete</i></a>
                            <a class="btn-floating btn-small waves-effect waves-light green"
                                href="{{ symptom_item.get_detail_url }}"><i class="material-icons">visibility</i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
    {% endblock %}